### ISSUE TITLE
Battery mod not working

### ISSUE THREAD

**Issue by maikramer** [DirtyUnicorns/android_device_motorola_nash#1]
In dirty unicorns the battery mod, the only one I have, is not working, can't even charge the mod.
In Aosip the mod works, then i tried du with aosip kernel but still not working. I think it's a user space problem, with permissions maybe.

Logs that can be useful :

mods_camd
type=1400 audit(0.0:8547): avc: granted { read open } for uid=1006 path="/dev/v4l-subdev15" dev="tmpfs" ino=13295 scontext=u:r:init:s0 tcontext=u:object_r:video_device:s0 tclass=chr_file

modcamd-misc_dev
open /dev/v4l2-hal-ctrl failed 2

In kernel:
 737.657536] init: Service 'mods_camd' (pid 9958) exited with status 0

[  747.491957] init: service mods_camd does not have a SELinux domain defined

**Comment by BoredOutOfMyGit** [comment]
Use JIRA to report any issues.

https://jira.dirtyunicorns.com
