### ISSUE TITLE
du.dependencies missing

### ISSUE THREAD

**Issue by TeamFahQ** [DirtyUnicorns/android_device_motorola_nash#2]
no du.dependencies files for branch p9x-caf. I searched gerrit for possible pending changes, but there are none concerning this file. Without it, one cannot properly sync/build for this device.

**Comment by BoredOutOfMyGit** [comment]
Did you stop to think that maybe this is done on purpose because is not ready? No, that makes too much sense though.

Closing this 'issue' up.
